name: "Build environment"
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - main

jobs:
  build_env:
    name: "Build ${{ matrix.os }}"
    strategy:
      fail-fast: False
      matrix:
        # When adding alternative OS, we also need an alternative for the installation of miniforge
        os: ["ubuntu-latest"]
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        # This is needed otherwise we can't activate the conda installation
        shell: bash -l {0}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # At 2025-05 a new token was added in the gitgub-action secrets. This token will expire ~05-2026.
      # When that happens, generate a new one following the documentation:
      # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
      - name: checkout development repository
        uses: actions/checkout@v3
        with:
          repository: ECA-D/development
          token: ${{ secrets.DEVELOPMENT_SECRET_TOKEN }}
          path: development
          ref: main
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        if: matrix.os == 'ubuntu-latest'
        with:

          installer-url: https://github.com/conda-forge/miniforge/releases/download/25.3.0-3/Miniforge3-Linux-x86_64.sh
          python-version: "3.11"
          allow-softlinks: true
          show-channel-urls: true
          auto-update-conda: true

      - name: install conda dependencies
        run: bash install_step0_conda.sh
      - name: install R dependencies
        run: bash install_step1_R.sh
      - name: run_test
        run: bash run_minimal_test.sh
      - name: Run development tests
        run: |
          which python
          python development/test.py

      - name: List full installation of the conda environment
        run: conda list
      - name: "completed"
        run: echo 'All complete, successful'
